defaults:
  - _self_
  - machine: lab1527


data:
  train_file: '../../data/neo_converted/nullptr_no_feature_whole.pkl'
  dev_file: '../../data/neo_converted/nullptr_no_feature_dev.pkl'
  test_file: '../../data/neo_converted/nullptr_no_feature_test.pkl'
  train_size: 8000
  dev_size: 2000

train:
  num_epochs: 4

  batch_size: 12
  num_workers: 1
  log_dir: "logs"
  num_checkpoints: 1
  every_n_train_steps: 100
  val_check_interval: 20
  learning_rate: 1e-4
  weight_decay: 0.0






model:
  vocab_size:
  embedding_dim: 768
  hidden_size: 1024
  checkpoint_path: "./checkpoints"



