defaults:
  - _self_
  - machine: lab1527


data:
  train_file: '../../data/neo_converted/nullptr_no_feature_whole.pkl'
  dev_file: '../../data/neo_converted/nullptr_no_feature_dev.pkl'
  test_file: '../../data/neo_converted/nullptr_no_feature_test.pkl'
  train_size:
  dev_size:

train:
  num_epochs: 50

  batch_size: 64
  num_workers: 4
  log_dir: "logs"
  num_checkpoints: 10
  every_n_train_steps: 10000
  val_check_interval: 10000
  learning_rate: 1e-4
  weight_decay: 0.0






model:
  vocab_size:
  embedding_dim: 1024
  hidden_size1: 256
  hidden_size2: 32
  checkpoint_path: "./checkpoints"



